## 해당 파일은 공용 파일로서, 애플리케이션이 어떤 이름이든 default 프로파일이면 조회된다.
## http://localhost:8888/{config server 의 이름}/default 로 불러올 수 있음
jwt:
  application: users-service
  expiration: 0
  secret: secret-key
  type: Bearer
  profile: defalut

application:
  name: application
  file: application.yml
  profile: default