## 해당 파일은 공용 파일로서,
##  http://localhost:8888/{config server 의 이름}/default 로 불러올 수 있음
jwt:
  application: config-service
  expiration: 360
  secret: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041492
  type: Bearer
  profile: defalut