## 해당 파일은 공용 파일로서, 애플리케이션이 어떤 이름이든 default 프로파일이면 조회된다.
## http://localhost:8888/{config server 의 이름}/default 로 불러올 수 있음
jwt:
  application: config-service
  expiration: 3600000
  secret: '{cipher}183658d5a1dd009969d8b59abbb41e38599964f63f485678e6b4dd24fef7de30'
  type: Bearer
  profile: defalut