spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1111
    url: jdbc:h2:tcp://localhost/~/ecommerce

jwt:
  application: users-service
  expiration: 3600000
  secret: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041492
  type: Bearer
  profile: default
