spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    # password: '{cipher}AQAsVN1ANqOcRTtZmc21PxUE2R8ws/u+FyANXVqoauUmxOH67olcLoCgEk4UqeHdk9FfZwbnr18Ty+itXsEJxl+TObQFAVmnwabdmjzrPAmL5PonHrHOmXiUf/lTYqbGta/8M3WaTrNkk3ULRCHpIbJUwJoT9qyPFDfRtBQ98BFOjwq1bnOGuKRn59jRe6u+EncHcDh+TAgpdoW0/T/ELYk0COrU3hFC/QoECh+CNcGdfqNFNgbJx5cm3Zg9d+XxOGxEVLFMSLl+pEjaqTM/mqqKv86G82Y5xJME8bahkk0rZuVIeT2XYvUN47J0FATy/AdD+YXuYtOm2nDn8ZCdiguwbdS31hZ+lAbPJon9eI0t9yr04scr6wEzrcscrsT+jlc='
    url: jdbc:h2:tcp://localhost/~/springcloud_ecommerce_users


jwt:
  application: users-service
  expiration: 3600000
  secret: secret-key
  type: Bearer
  profile: defalut

application:
  name: users-service
  file: users-service-default.yml
  profile: default